version: "3.9"

services:
  localstack:
    image: localstack/localstack  # name and tag of LocalStack Docker image to use
    container_name: localstack  # the main docker container name
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    environment:
      - PORT_WEB_UI=9000
      - LAMBDA_EXECUTOR=local  # the lambda code is executed directly in the context of LocalStack itself