server:
  port: 8081

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB


logging:
  level:
    root=debug:

# override by profile configs
aws:
  credentials:
    access-key:
    secret-key:
  s3:
    endpoint: dummy-s3
  dynamodb:
    endpoint: dummy-dynamodb
  region: region
