server:
  port: 8081

servlet:
  multipart-max-file-size: 50MB

logging:
  level:
    root=debug:

# override by profile configs
aws:
  credentials:
    access-key:
    secret-key:
  s3:
    endpoint: dummy-s3
  dynamodb:
    endpoint: dummy-dynamodb
  region: region
